import { EventCategoryType, RoleStatus } from '@job-tracker/domain';

import { EventTypeDocument } from './documents/event-type.document';

/**
 * SEED DATA LOCALIZATION NOTE:
 * The 'translationKey' field for system-defined types MUST correspond to a key
 * in the 'SystemEventTypes' namespace within the i18n message files
 * (e.g., apps/web-ui/messages/en-US.json).
 *
 * If you add a new seeded event type here, ensure you add the corresponding
 * translations in all supported languages.
 */
export const seedEventTypes: EventTypeDocument[] = [
  // Application
  {
    id: '3b2d1c6e-4f5a-4b7c-8d9e-0f1a2b3c4d5e',
    serverId: null,
    updatedAt: new Date().toISOString(),
    name: 'Job Lead',
    translationKey: 'jobLead',
    category: EventCategoryType.Application,
    targetStatus: RoleStatus.Lead,
    isSystemDefined: true,
    isCommon: false,
  },
  {
    id: '5c3e2d7f-5a6b-5c8d-9e0f-1a2b3c4d5e6f',
    serverId: null,
    updatedAt: new Date().toISOString(),
    name: 'Applied',
    translationKey: 'applied',
    category: EventCategoryType.Application,
    targetStatus: RoleStatus.Applied,
    isSystemDefined: true,
    isCommon: true,
  },
  {
    id: '7ff1f978-029e-484e-9dee-f6fb373f5444',
    serverId: null,
    updatedAt: new Date().toISOString(),
    name: 'Application Viewed',
    translationKey: 'applicationViewed',
    category: EventCategoryType.Application,
    targetStatus: RoleStatus.Applied,
    isSystemDefined: true,
    isCommon: false,
  },
  {
    id: '7fc6b92d-61cb-4122-bb17-b644a7e56666',
    serverId: null,
    updatedAt: new Date().toISOString(),
    name: 'Recruiter Screening Scheduled',
    translationKey: 'recruiterScreeningScheduled',
    category: EventCategoryType.Application,
    targetStatus: RoleStatus.Applied,
    isSystemDefined: true,
    isCommon: false,
  },

  // Communication
  {
    id: '7d4f3e80-6b7c-6d9e-0f1a-2b3c4d5e6f7a',
    serverId: null,
    updatedAt: new Date().toISOString(),
    name: 'Recruiter Outreach',
    translationKey: 'recruiterOutreach',
    category: EventCategoryType.Communication,
    isSystemDefined: true,
    isCommon: false,
  },
  {
    id: '9e5a4f91-7c8d-7e0f-1a2b-3c4d5e6f7a8b',
    serverId: null,
    updatedAt: new Date().toISOString(),
    name: 'Networking/Coffee Chat',
    translationKey: 'networkingCoffeeChat',
    category: EventCategoryType.Communication,
    isSystemDefined: true,
    isCommon: false,
  },
  {
    id: 'af6b5f02-8d9e-8f1a-2b3c-4d5e6f7a8b9c',
    serverId: null,
    updatedAt: new Date().toISOString(),
    name: 'Follow-up Sent',
    translationKey: 'followUpSent',
    category: EventCategoryType.Communication,
    isSystemDefined: true,
    isCommon: false,
  },
  {
    id: 'c30498f4-8784-465a-a513-d665999bb5be',
    serverId: null,
    updatedAt: new Date().toISOString(),
    name: 'Email Received',
    translationKey: 'emailReceived',
    category: EventCategoryType.Communication,
    isSystemDefined: true,
    isCommon: false,
  },
  {
    id: 'a903ec72-57c1-4ed4-8de9-b559b989d8e7',
    serverId: null,
    updatedAt: new Date().toISOString(),
    name: 'Email Sent',
    translationKey: 'emailSent',
    category: EventCategoryType.Communication,
    isSystemDefined: true,
    isCommon: false,
  },
  {
    id: 'aafe028c-bb68-43a3-bd0d-cfd64c349b40',
    serverId: null,
    updatedAt: new Date().toISOString(),
    name: 'Phone Call',
    translationKey: 'phoneCall',
    category: EventCategoryType.Communication,
    isSystemDefined: true,
    isCommon: false,
  },

  // Interview
  {
    id: 'bd7c6f13-9e0f-9a2b-3c4d-5e6f7a8b9c0d',
    serverId: null,
    updatedAt: new Date().toISOString(),
    name: 'Technical Assessment',
    translationKey: 'technicalAssessment',
    category: EventCategoryType.Interview,
    targetStatus: RoleStatus.Interviewing,
    isSystemDefined: true,
    isCommon: false,
  },
  {
    id: 'ce8d7f24-0f1a-0b3c-4d5e-6f7a8b9c0d1e',
    serverId: null,
    updatedAt: new Date().toISOString(),
    name: 'Screening Call',
    translationKey: 'screeningCall',
    category: EventCategoryType.Interview,
    targetStatus: RoleStatus.Interviewing,
    isSystemDefined: true,
    isCommon: false,
  },
  {
    id: 'df9e8f35-1a2b-1c4d-5e6f-7a8b9c0d1e2f',
    serverId: null,
    updatedAt: new Date().toISOString(),
    name: 'Technical Interview',
    translationKey: 'technicalInterview',
    category: EventCategoryType.Interview,
    targetStatus: RoleStatus.Interviewing,
    isSystemDefined: true,
    isCommon: true,
  },
  {
    id: 'e0af9f46-2b3c-2d5e-6f7a-8b9c0d1e2f3a',
    serverId: null,
    updatedAt: new Date().toISOString(),
    name: 'Onsite Interview',
    translationKey: 'onsiteInterview',
    category: EventCategoryType.Interview,
    targetStatus: RoleStatus.Interviewing,
    isSystemDefined: true,
    isCommon: true,
  },
  {
    id: 'f2c7b068-4d5e-4f6f-8a9b-0c1d2e3f4a5b',
    serverId: null,
    updatedAt: new Date().toISOString(),
    name: 'Interview Scheduled',
    translationKey: 'interviewScheduled',
    category: EventCategoryType.Interview,
    targetStatus: RoleStatus.Interviewing,
    isSystemDefined: true,
    isCommon: false,
  },
  {
    id: 'f3d8c179-5e6f-5a7b-9c0d-1e2f3a4b5c6d',
    serverId: null,
    updatedAt: new Date().toISOString(),
    name: 'Interview Completed',
    translationKey: 'interviewCompleted',
    category: EventCategoryType.Interview,
    targetStatus: RoleStatus.Interviewing,
    isSystemDefined: true,
    isCommon: false,
  },

  // Outcomes
  {
    id: 'f1bfaf57-3c4d-3e6f-7a8b-9c0d1e2f3a4b',
    serverId: null,
    updatedAt: new Date().toISOString(),
    name: 'Offer Received',
    translationKey: 'offerReceived',
    category: EventCategoryType.Outcome,
    targetStatus: RoleStatus.Offer,
    isSystemDefined: true,
    isCommon: true,
  },
  {
    id: 'a1b2c3d4-e5f6-47a8-b9c0-d1e2f3a4b5c6',
    serverId: null,
    updatedAt: new Date().toISOString(),
    name: 'Not Selected',
    translationKey: 'notSelectedReceived',
    category: EventCategoryType.Outcome,
    targetStatus: RoleStatus.NotSelected,
    isSystemDefined: true,
    isCommon: false,
  },
  {
    id: '0c1d2e3f-4a5b-6c7d-8e9f-0a1b2c3d4e5f',
    serverId: null,
    updatedAt: new Date().toISOString(),
    name: 'Offer Accepted',
    translationKey: 'offerAccepted',
    category: EventCategoryType.Outcome,
    targetStatus: RoleStatus.Accepted,
    isSystemDefined: true,
    isCommon: false,
  },
  {
    id: '13dfcf79-5e6f-5a8b-9c0d-1e2f3a4b5c6d',
    serverId: null,
    updatedAt: new Date().toISOString(),
    name: 'Not Selected',
    translationKey: 'notSelected',
    category: EventCategoryType.Outcome,
    targetStatus: RoleStatus.NotSelected,
    isSystemDefined: true,
    isCommon: true,
  },
  {
    id: '24efdf8a-6f7a-6b9c-0d1e-2f3a4b5c6d7e',
    serverId: null,
    updatedAt: new Date().toISOString(),
    name: 'Withdrew Application',
    translationKey: 'withdrewApplication',
    category: EventCategoryType.Outcome,
    targetStatus: RoleStatus.Withdrawn,
    isSystemDefined: true,
    isCommon: false,
  },
];
